thy = input() 
import turtle 
wn = turtle.Screen() 
wn.bgcolor("black")
thuy = turtle.Turtle()
thuy.color("white")
thuy.shape("circle")
thuy.shapesize(0.000001)
if thy == "a" :
    thuy.left(60)
    thuy.forward(100)
    thuy.right(120)
    thuy.forward(100)
    thuy.penup()
    thuy.right(120)
    thuy.forward(100)
    thuy.right(120)
    thuy.forward(40)
    thuy.pendown()
    thuy.right(60)
    thuy.forward(60)
elif thy == "b":
    thuy.right(100)
    thuy.forward(100) 
wn.exitonclick() 
